sudo: required

language: csharp
matrix:
  include:
    - os: linux
      dotnet: 2.2.301
      mono: none
      dist: bionic
before_install:
  - ./.travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - dotnet restore ./LiteDB/LiteDB.csproj
  - dotnet build ./LiteDB/LiteDB.csproj -f netstandard2.0
  - dotnet restore ./LiteDB.Tests/LiteDB.Tests.csproj
  - dotnet build ./LiteDB.Tests/LiteDB.Tests.csproj
  - dotnet test ./LiteDB.Tests/LiteDB.Tests.csproj --logger:console;verbosity=normal

notifications:
  email: false  
